# Generated by Django 3.1.7 on 2021-02-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problems.category'),
            preserve_default=False,
        ),
    ]
