# Generated by Django 3.1.7 on 2021-02-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.category'),
        ),
    ]
